run:
  # timeout for analysis
  deadline: 4m
  build-tags:
    - autopilotrpc
    - chainrpc
    - invoicesrpc
    - neutrinorpc
    - peersrpc
    - signrpc
    - walletrpc
    - watchtowerrpc

linters-settings:
  govet:
    # Don't report about shadowed variables
    check-shadowing: false
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

linters:
  enable-all: true
  disable:
    # Init functions are used by loggers throughout the codebase.
    - gochecknoinits

    # Global variables are used by loggers.
    - gochecknoglobals

    # Some lines are over 80 characters on purpose and we don't want to make
    # them even longer by marking them as 'nolint'.
    - lll

    # We don't care (enough) about misaligned structs to lint that.
    - maligned

    # We have long functions, especially in tests. Moving or renaming those
    # would trigger funlen problems that we may not want to solve at that time.
    - funlen

    # Gosec is outdated and reports false positives.
    - gosec

issues:
  # Only show newly introduced problems.
  new-from-rev: 4008b92d81d4d62e663025c5f79ebe44b53f283c
