name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

defaults:
  run:
    shell: bash

env:
  # go needs absolute directories, using the $HOME variable doesn't work here.
  GOCACHE: /home/runner/work/go/pkg/build
  GOPATH: /home/runner/work/go
  GO_VERSION: 1.21

jobs:
  ########################
  # build pkg and wasm bin
  ########################
  build:
    name: build package and wasm
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: go cache
        uses: actions/cache@v3
        with:
          path: /home/runner/work/go
          key: lnc-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            lnc-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-${{ hashFiles('**/go.sum') }}
            lnc-${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ github.job }}-
            lnc-${{ runner.os }}-go-${{ env.GO_VERSION }}-
            lnc-${{ runner.os }}-go-

      - name: setup go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: '~${{ env.GO_VERSION }}'
      # test
      - name: wasm wasi compile
        run: make wasi

